// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.rpc.test.RPCTest in rpc/test/test.proto
package gg.strims.rpc.test

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.GrpcStreamingCall

class GrpcRPCTestClient(
  private val client: GrpcClient
) : RPCTestClient {
  override fun CallUnary(): GrpcCall<RPCCallUnaryRequest, RPCCallUnaryResponse> =
      client.newCall(GrpcMethod(
      path = "/strims.rpc.test.RPCTest/CallUnary",
      requestAdapter = RPCCallUnaryRequest.ADAPTER,
      responseAdapter = RPCCallUnaryResponse.ADAPTER
  ))

  override fun CallStream(): GrpcStreamingCall<RPCCallStreamRequest, RPCCallStreamResponse> =
      client.newStreamingCall(GrpcMethod(
      path = "/strims.rpc.test.RPCTest/CallStream",
      requestAdapter = RPCCallStreamRequest.ADAPTER,
      responseAdapter = RPCCallStreamResponse.ADAPTER
  ))
}
