// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.rpc.test.RPCTest in rpc/test/test.proto
package gg.strims.rpc.test

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcStreamingCall
import com.squareup.wire.Service

interface RPCTestClient : Service {
  fun CallUnary(): GrpcCall<RPCCallUnaryRequest, RPCCallUnaryResponse>

  fun CallStream(): GrpcStreamingCall<RPCCallStreamRequest, RPCCallStreamResponse>
}
